name = "cdni"
compatibility_date = "2026-01-31"

# Para Cloudflare Pages (sirve los .html desde la raíz)
pages_build_output_dir = "."

# D1 (reemplaza database_id por el ID real de tu D1)
[[d1_databases]]
binding = "DB"
database_name = "prepa_db"
database_id = "b83d03f2-0f13-4404-8e6a-cd2b697446df"

# R2 Bucket para archivos (imágenes, videos, PDFs)
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "cdni-files"
